INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (1, 1, 'response 1', 1);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (2, 1, 'response 1', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (3, 1, 'response 1', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (4, 1, 'response 1', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (5, 4, '3.14', 1);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (6, 4, '3.18', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (7, 5, ' A JavaScript library', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (8, 5, 'A programming language', 1);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (9, 5, ' A browser extension', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (10, 5, ' A markup language', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (11, 6, 'var', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (12, 6, 'obj', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (13, 6, 'const', 1);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (14, 6, 'variable', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (15, 7, 'Java', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (16, 7, 'Python', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (17, 7, 'C#', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (18, 7, 'Javascript', 1);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (19, 8, 'bool', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (20, 8, 'boolean', 1);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (21, 8, 'bit', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (22, 8, 'boolen', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (23, 9, 'To define a new class', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (24, 9, ' To define a new variable', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (25, 9, 'To define a contract for object structure', 1);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (26, 9, 'To define a loop', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (27, 12, 'To declare a function', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (28, 12, 'To define a new interface', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (29, 12, 'To define a new object', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (30, 12, 'To define a new class', 1);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (31, 13, 'Inheritance', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (32, 13, 'Abstract classes', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (33, 13, 'Interfaces', 1);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (34, 13, 'Type guards', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (35, 14, 'By using the "nonull" modifier', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (36, 14, 'By using the "non-nullable" type', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (37, 14, 'By using the "strict" mode', 0);
INSERT INTO quiz.choices (choice_id, question_id, choices, is_correct) VALUES (38, 14, 'By using the "!" symbol after the data type', 1);
